# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-organization-access-role
  description: Terraform module to create an IAM Role to grant permissions to delegated IAM users in the master account to access an invited member account
  homepage: https://cloudposse.com/accelerate
  topics: aws, role, policy, permissions, aws-iam



